# Generated by Django 2.2 on 2019-04-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='high_score',
            field=models.IntegerField(null=True),
        ),
    ]
